version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: vps-nginx-test
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - vps-network

  certbot:
    image: certbot/certbot:latest
    container_name: vps-certbot-test
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email artur.komarovv@gmail.com --agree-tos --no-eff-email -d botinger789298.work.gd
    depends_on:
      - nginx
    networks:
      - vps-network

  # Cockpit эмуляция для тестирования
  cockpit:
    image: quay.io/cockpit/ws:latest
    container_name: vps-cockpit-test
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - COCKPIT_CERTIFICATE_FILE=/etc/cockpit/ws-certs.d/server.crt
      - COCKPIT_PRIVATE_KEY_FILE=/etc/cockpit/ws-certs.d/server.key
    restart: unless-stopped
    networks:
      - vps-network
    privileged: true

networks:
  vps-network:
    driver: bridge

volumes:
  letsencrypt:
  html: