version: "3.8"

services:
  marzban:
    build:
      context: .
      dockerfile: Dockerfile
    image: komarovai/marzban-custom:latest
    container_name: marzban
    restart: unless-stopped
    environment:
      - MARZBAN_QUIC=true
      - MARZBAN_DB_URL=sqlite:////var/lib/marzban/marzban.db
      - MARZBAN_HOST=${DOMAIN_NAME}
      - MARZBAN_PANEL_PORT=${MARZBAN_PANEL_PORT:-8000}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - XRAY_REALITY_PRIVATE_KEY=${XRAY_REALITY_PRIVATE_KEY:-}
      - XRAY_REALITY_PUBLIC_KEY=${XRAY_REALITY_PUBLIC_KEY:-}
      - XRAY_REALITY_SHORT_IDS=${XRAY_REALITY_SHORT_IDS:-}
      - XRAY_REALITY_SERVER_NAMES=${XRAY_REALITY_SERVER_NAMES:-google.com,www.google.com}
      - XRAY_PORT=${XRAY_PORT:-2083}
      - XRAY_JSON=${XRAY_JSON:-}
      - XRAY_VLESS_REALITY=true
      - XRAY_GRPC_ENABLE=true
    volumes:
      - ./data:/var/lib/marzban
      - ./xray:/etc/xray
      - ./logs:/opt/marzban/logs
    ports:
      - "${MARZBAN_PANEL_PORT:-8000}:8000"
      - "${XRAY_PORT:-2083}:${XRAY_PORT:-2083}"
    networks:
      - marzban-network
    healthcheck:
      test: ["CMD", "curl", "-sS", "-o", "/dev/null", "-w", "%{http_code}", "http://127.0.0.1:8000/api/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  marzban-network:
    driver: bridge
