services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    environment:
      - MARZBAN_QUIC=true
      - MARZBAN_DB_URL=sqlite:////var/lib/marzban/db.sqlite3
      - MARZBAN_HOST=${DOMAIN_NAME:-0.0.0.0}
      - MARZBAN_PANEL_PORT=${MARZBAN_PANEL_PORT:-8000}
      - DOMAIN_NAME=${DOMAIN_NAME:-}
      - XRAY_REALITY_PRIVATE_KEY=${XRAY_REALITY_PRIVATE_KEY:-}
      - XRAY_REALITY_PUBLIC_KEY=${XRAY_REALITY_PUBLIC_KEY:-}
      - XRAY_REALITY_SHORT_IDS=${XRAY_REALITY_SHORT_IDS:-}
      - XRAY_REALITY_SERVER_NAMES=${XRAY_REALITY_SERVER_NAMES:-google.com,www.google.com}
      - XRAY_PORT=${XRAY_PORT:-2083}
      - XRAY_VLESS_REALITY=true
      - XRAY_GRPC_ENABLE=true
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./xray:/etc/xray
      - ./logs:/opt/marzban/logs
    ports:
      - "${MARZBAN_PANEL_PORT:-8000}:8000"
      - "${XRAY_PORT:-2083}:${XRAY_PORT:-2083}"
    networks:
      - marzban-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://127.0.0.1:8000/api/admin', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  marzban-network:
    driver: bridge