version: "3.8"

services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    environment:
      - MARZBAN_QUIC=true
      - MARZBAN_DB_URL=sqlite:////var/lib/marzban/marzban.db
      - MARZBAN_HOST=${DOMAIN_NAME}
      - MARZBAN_PANEL_PORT=443
      - XRAY_REALITY_PRIVATE_KEY=${XRAY_REALITY_PRIVATE_KEY}
      - XRAY_REALITY_SHORT_IDS=${XRAY_REALITY_SHORT_IDS}
      - XRAY_REALITY_SERVER_NAMES=${XRAY_REALITY_SERVER_NAMES}
      - XRAY_PORT=443
      - XRAY_VLESS_REALITY=true
      - XRAY_GRPC_ENABLE=true
    volumes:
      - ./data:/var/lib/marzban
      - ./xray:/etc/xray
    network_mode: host

  reality-keygen:
    image: teddysun/xray:latest
    container_name: reality-keygen
    command: sh -c "xray x25519 | tee /keys/out && tail -f /dev/null"
    volumes:
      - ./keys:/keys
    restart: "no"
